# Generated by Django 5.0 on 2024-01-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
    ]
