# Generated by Django 5.0 on 2023-12-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
